### ISSUE TITLE
Installation doesn't work on Mac

### ISSUE THREAD

**Issue by NicholasLYang** [rob2d/generator-react-redux-gulp#1]
Get following error when trying to install on mac:

    AssertionError: Trying to copy from a source that does not exist: 
    /usr/local/lib/node_modules/generator-react-redux-gulp/app/templates/.gitignore
        at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-react-redux-
    gulp/node_modules/mem-fs-editor/lib/actions/copy.js:47:3)
        at copyFromTemplate (/usr/local/lib/node_modules/generator-react-redux-
    gulp/app/index.js:31:21)
        at copyFiles (/usr/local/lib/node_modules/generator-react-redux-gulp/app/index.js:72:14)
        at Object.<anonymous> (/usr/local/lib/node_modules/generator-react-redux-
    gulp/node_modules/yeoman-generator/lib/index.js:417:23)
        at /usr/local/lib/node_modules/generator-react-redux-gulp/node_modules/run-
    async/index.js:25:25
        at /usr/local/lib/node_modules/generator-react-redux-gulp/node_modules/run-
    async/index.js:24:19
        at /usr/local/lib/node_modules/generator-react-redux-gulp/node_modules/yeoman-
    generator/lib/index.js:418:9
        at runCallback (timers.js:666:20)
        at tryOnImmediate (timers.js:639:5)
        at processImmediate [as _immediateCallback] (timers.js:611:5)](url)

**Comment by rob2d** [comment]
Thanks Nick. I just tried to resolve the issue; apparently to reference a relative template folder in Yeoman in a non OS-specific way. The paths should be wrapped in `this.templatePath()`.

Please let me know if things work out now (v0.0.9 is also current on npm so normal install method should work).

**Comment by rob2d** [comment]
~Sorry, that wasn't actually the solution -- seems `this.templatePath` has an issue parsing globs. Have some other things in mind and will attempt those fixes later today.~

Actually, it seems I just had a preceding `/` on my source path on that entry after the fix yesterday which Yeoman perceives as an absolute path 😅  Fixed. 

Check it out and let me know if it works so we can close the issue.
