### ISSUE TITLE
Add above the fold CSS inlining 

### ISSUE THREAD

**Issue by NicholasLYang** [rob2d/generator-react-redux-gulp#12]
We should take `main-index.css` and any other CSS files and inline them above the fold on index.html (maybe with an optional flag so that people can disable it as needed)

**Comment by rob2d** [comment]
I think this ventures into the purely subjective. It's fine to have one or two CSS files; especially if they are above 10kb in file size. But HTML requests can run at least safely up to 4 items on modern browsers in parallel so is it worth it? 

It's also useful to have a central global CSS declaration file to edit (vs inline). JSS is nice but it's not rendered until build.js is complete and those styles declared in main are sensible defaults used throughout an app. 

Let's say you had a responsive layout for example: the min-sm and max-sm are useful for hiding/displaying content appropriately before content has loaded. Or if there is a preference (usually sensible/preferable) to omit padding/margins injected by default into tables/other things to zero.  JSS for global style isn't as efficient and plugins are kept optional so a main CSS is still a good starting point for some of these baselines.

**Comment by rob2d** [comment]
Closed, but am open to PR to minimize/clean up CSS and as always we can discuss in PM. Thanks for bringing up the concern though.
