### ISSUE TITLE
auto refresh issue

### ISSUE THREAD

**Issue by SatishDhiman** [rob2d/generator-react-redux-gulp#6]
Hi 
when we try to change in any component then it does't  pick the updated changes.
pls let me how to sort out this problem

**Comment by rob2d** [comment]
I'm sorry, this isn't really providing enough revelant information. Please elaborate. e.g. what steps are you taking? if this is an issue with ReactLiveReload that may be an issue to open on that. If you are not getting any updates, please make sure you are following instructions in the README. This repo is not for general IT support or beginners getting started in React.
