### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by squirrelsquirrel78** [rob2d/generator-react-redux-gulp#7]
An error occurred during build: `'import' and 'export' may appear only with 'sourceType: module'`. Here is the source code <a href="https://github.com/stuyspec/client-app/commit/e194c07f8fce0b03c1e65a91eddb9823f4de13ca">with</a> the error, and here is the source code <a href="https://github.com/stuyspec/client-app/commit/db91cb911e37c737edf7c55fbc8cf89bbf7f4998">without</a>. The error popped up when I imported two icons from the node module `react-icons` in `modules/core/componentsMastheadBar.js`.

**Comment by rob2d** [comment]
Thanks for the detailed explanation with this. I will try to get some time today to investigate. The first thing to check might be whether there is an issue with the library imported here ('react-icons'). Otherwise, it seems this is babel-related. A bit strange though since I've used a few hundred packages without issue so far...

**Comment by rob2d** [comment]
https://github.com/gorangajic/react-icons/issues/98

seems related. There was a PR to alleviate this issue but the author never used it. node_modules should be built into es5 at least in their npm build script if they aren't written that way by default. Seems the react-icons package isn't maintained properly, that may be a separate issue. Did you try manually building code from this npm dependency?

**Comment by squirrelsquirrel78** [comment]
Yes, it is a separate issue; I manually built the [icon code](https://github.com/stuyspec/client-app/commit/871bbc475d3a5c0926dd507358d7404370279dbf) and no bundle error was thrown. Thank you!

**Comment by rob2d** [comment]
No problem 👌 Thanks a lot for raising the issue in either case. It's something to keep an eye out for in regards to Babel changes in the future.
